paths:
  data: data
  collections: content
  layouts: layouts
  static: static
  uploads: static/uploads
  includes: layouts
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    icon: notes
    output: true
    filter: strict
    parse_branch_index: true
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
  paintings:
    path: content/paintings
    icon: notes
    output: true
    add_options:
      - name: Add painting
        editor: data
      - name: Add series info
        editor: data
        schema: series_info
    # Hide the content and visual area, instead only show front matter fields in editor
    _enabled_editors:
      - visual
      - data
    create:
      path: '{painting_series}/{painting_series}_no{number}/index.md'
      _inputs:
        painting_series:
          type: text
          comment: >-
            Add the name of the series (must be lowercase and multiple words
            seperated by an underscore).
          cascade: true
        number:
          type: number
          label: Painting number
          comment: Add the number of the painting in the series.
          cascade: true
    disable_add: false
    # Disable add button to prevent new folders from being created
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/paintings.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
        _inputs:
          image:
            type: image
            options:
              paths:
                uploads: '[base_path]/'
                static: ''
            cascade: true
      series_info:
        path: .cloudcannon/schemas/series-info.md
        # Default path when creating new files in this schema
        create:
          path: '{painting_series}/_index.md'
        # Hide the content and visual area, instead only show front matter fields in editor
        _enabled_editors:
          - data
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
timezone: Europe/London
_snippets_imports:
  hugo: false
