_snippets_imports:
  hugo: false
paths:
  data: data
  collections: content
  layouts: layouts
  static: static
  uploads: static/uploads
  includes: layouts
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  paintings:
    path: content/paintings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/paintings.md
        _inputs:
          image:
            type: image
            options:
              paths:
                static: ''
                uploads: '[base_path]/'
    create:
      path: '{painting_series}/{painting_series}_no{number}/index.md'
      _inputs:
        painting_series:
          type: text
        number: 
          type: number
          label: Painting number
    # create:
    #   path: '{painting_series}/{painting_series}_no{number}/index.md'
    #   _inputs:
    #     painting_series:
    #       type: select
    #       options:
    #         values:
    #           - cobogo
    #           - figures
    #     number: 
    #       type: number
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
data_config: {}
timezone: Europe/London
