paths:
  data: data
  collections: content
  layouts: layouts
  static: static
  uploads: static/uploads
  includes: layouts
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  paintings:
    path: content/paintings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
data_config: {}
timezone: Etc/UTC
